### PR TITLE
Drop the use of Bignum in CashAddr encoding

### PR DESCRIPTION
**Pull request by DesWurstes**
It improves the PolyMod generation while making it even more readable. I aimed the polymod function to strictly return a number; if you didn't like that part, let me know, and it'll simply return an array.

### CODE REVIEW

**Comment by matiu** [comment]
Thanks a lot for the contribution!

Is this change objective is to improve performance? If so, can you benchmark the results?

**Comment by DesWurstes** [comment]
On Firefox, it's 240 times faster, on Chrome, it's 80 times faster: https://jsperf.com/bn-polymod-vs-pure-js-polymod

**Comment by matiu** [comment]
LGTM, but I would like to get 2 more reviews.

**Comment by bitjson** [comment]
LGTM – awesome work @DesWurstes!

Looks like the Cashaddr spec has some [new, larger test vectors](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md#larger-test-vectors) as of June 4. It would probably be a good idea to get those integrated into the tests at `test/address.js`. (I don't really think that needs to hold up the PR, but it's my only reservation.)

**Comment by ryanxcharles** [comment]
I issued a PR to the PR adding test vectors here:

https://github.com/DesWurstes/bitcore-lib-cash/pull/1

I approve this pull request and would like to see this merged.

(If someone can explain what is type "15" that would be greatly appreciated).

**Review by bitjson — APPROVED** [review]
Perfect! Thanks for the additional tests @ryanxcharles.  @matiu 👍 for merge.

**Pull request merged**
